# Generated by Django 4.0.5 on 2022-07-07 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blok_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_week', models.IntegerField(verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Блок времени',
                'verbose_name_plural': 'Блоки времени',
            },
        ),
        migrations.CreateModel(
            name='LessonNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер урока')),
                ('time_start', models.CharField(blank=True, max_length=250, verbose_name='Время начала')),
                ('time_end', models.CharField(blank=True, max_length=250, verbose_name='Время окончания')),
            ],
            options={
                'verbose_name': 'Номер урока',
                'verbose_name_plural': 'Номера уроков',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='nClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Класс')),
                ('isClub', models.BooleanField(blank=True, null=True, verbose_name='Это кружок?')),
                ('digit', models.IntegerField(blank=True, null=True, verbose_name='Цифра')),
                ('size', models.IntegerField(blank=True, null=True, verbose_name='Численность')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('spec', models.ManyToManyField(related_name='spec_for_subjects', to='timetable.specialization', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=250, verbose_name='Фамилия')),
                ('name2', models.CharField(max_length=250, verbose_name='Имя')),
                ('name3', models.CharField(blank=True, max_length=250, verbose_name='Отчество')),
                ('time_work', models.CharField(blank=True, max_length=250, null=True, verbose_name='Стаж работы')),
                ('hard_time', models.IntegerField(blank=True, null=True, verbose_name='Занятость')),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль учителя',
                'verbose_name_plural': 'Учтеля',
            },
        ),
        migrations.CreateModel(
            name='TypeOfRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип пожелания',
                'verbose_name_plural': 'Типы пожеланий',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_total', models.IntegerField(blank=True, verbose_name='Всего времени')),
                ('time_now', models.IntegerField(blank=True, null=True, verbose_name='Осталось/прошло')),
                ('ncls', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.nclass', verbose_name='Класс')),
                ('subj', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.subjects', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Элемент учебного плана',
                'verbose_name_plural': 'Учебный план',
                'ordering': ['time_total'],
            },
        ),
        migrations.CreateModel(
            name='TeacherRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Коментарий')),
                ('lavel_value', models.IntegerField(blank=True, verbose_name='Уровень важностьи')),
                ('teacer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.teacherprofile', verbose_name='Учитель')),
                ('time', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.blok_time', verbose_name='Время')),
                ('type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.typeofrequest', verbose_name='Тип пожелания')),
            ],
            options={
                'verbose_name': 'Пожелание',
                'verbose_name_plural': 'Пожелания',
            },
        ),
        migrations.CreateModel(
            name='Teacher_Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nclass', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.nclass', verbose_name='Класс')),
                ('subject', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.subjects', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.teacherprofile', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Занятие учителя',
                'verbose_name_plural': 'Занятия учителей',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numb', models.CharField(max_length=250, verbose_name='Номер комнаты')),
                ('count', models.IntegerField(verbose_name='Вместимость')),
                ('spec', models.ManyToManyField(to='timetable.specialization', verbose_name='Специализация')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
                'ordering': ['numb'],
            },
        ),
        migrations.AddField(
            model_name='nclass',
            name='class_teacher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_teacher', to='timetable.teacherprofile', verbose_name='Классынй руководитель'),
        ),
        migrations.CreateModel(
            name='Blok_timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_week', models.IntegerField(blank=True, default=None, null=True, verbose_name='День недели')),
                ('blok_time', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.blok_time', verbose_name='Блок времени')),
                ('lesson_number', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lesson_numb', to='timetable.lessonnumber', verbose_name='Номер урока')),
                ('nclass', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.nclass', verbose_name='Класс')),
                ('room', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.room', verbose_name='Кабинет')),
                ('subject', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.subjects', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.teacherprofile', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Блок расписания',
                'verbose_name_plural': 'Блоки расписаний',
            },
        ),
        migrations.AddField(
            model_name='blok_time',
            name='lesson_number',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lesson_number', to='timetable.lessonnumber', verbose_name='Номер урока'),
        ),
    ]
